-   id: dart-format
    name: Format Dart Code
    entry: dart_format
    language: python
    files: \.dart$
-   id: sort_imports
    name: Sort Dart Imports
    entry: sort_imports
    language: python
    files: \.dart$
-   id: dart-analyze
    name: Analyze Dart Code
    entry: dart_analyze
    language: python
    files: \.dart$